### PR TITLE
deps: bump celestia-node & local-celestia-devnet image version to v0.10.0

### PR DESCRIPTION
**Pull request by jcstein**
## Overview

This PR updates the `celestia-node` image from `v0.9.5` to `v0.10.0`. It also replaces the RPC with an RPC URL that does not result in a `max_subscriptions` error.

## Checklist

- [x] New and updated code has appropriate documentation
- [x] New and updated code has new and/or updated testing
- [x] Required CI checks are passing
- [x] Visual proof for any user facing features like CLI or documentation updates
- [x] Linked issues closed with keywords

### CODE REVIEW

**Comment by jcstein** [comment]
Full logs from an overnight run can be found here https://github.com/jcstein/logs/blob/main/v0.10.0-logs.log

**Comment by jcstein** [comment]
```bash
root@jcs-optimism:~/optimism# cast block latest --rpc-url http://localhost:9545 --field number             [38/1906]
25465
root@jcs-optimism:~/optimism# cast block safe --rpc-url http://localhost:9545 --field number
157
```

**Comment by jcstein** [comment]
image

Successful run with no errors on devnet.

**Review by tuxcanfly — APPROVED** [review]
OK.

**Pull request merged**
