### PR TITLE
testnet: bump block time from 3s to 15s

### PR DESCRIPTION
**Pull request by tuxcanfly**
## Overview

Bumped the blocktime for testnet script from 3s to 15s so that batcher doesn't congest on publishing data to celestia.

## Checklist

- [x] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [x] Required CI checks are passing
- [x] Visual proof for any user facing features like CLI or documentation updates
- [x] Linked issues closed with keywords

### CODE REVIEW

**Comment by jcstein** [comment]
Do we need to also change anything in https://github.com/celestiaorg/optimism/blob/cb828725e8df901a3cf97529f281babbd7fcb64f/bedrock-devnet/devnet/__init__.py#L51-L52 and create a `testnetL1.ts` file (done in https://github.com/celestiaorg/optimism/pull/49/commits/d067ccc17a539ea025eaaa5828e85dbc9e67087f) https://github.com/celestiaorg/optimism/blob/cb828725e8df901a3cf97529f281babbd7fcb64f/packages/contracts-bedrock/deploy-config/devnetL1.ts#L2?

**Comment by jcstein** [comment]
or https://github.com/celestiaorg/optimism/blob/cb828725e8df901a3cf97529f281babbd7fcb64f/bedrock-devnet/devnet/__init__.py#L29 or https://github.com/celestiaorg/optimism/blob/cb828725e8df901a3cf97529f281babbd7fcb64f/bedrock-devnet/devnet/__init__.py#L64 or add anything here https://github.com/celestiaorg/optimism/blob/cb828725e8df901a3cf97529f281babbd7fcb64f/packages/contracts-bedrock/hardhat.config.ts#L38
or https://github.com/celestiaorg/optimism/blob/cb828725e8df901a3cf97529f281babbd7fcb64f/packages/sdk/hardhat.config.ts#L18 or https://github.com/celestiaorg/optimism/blob/cb828725e8df901a3cf97529f281babbd7fcb64f/packages/sdk/hardhat.config.ts#L47?

**Review by jcstein — CHANGES_REQUESTED** [review]
left comments to address, most were outside of relevant files in PR, which is why they are comments

**Comment by jcstein** [comment]
Thinking we could also add this:

```Makefile
test-integration:
	bash ./ops-bedrock/test-integration.sh \
		./packages/contracts-bedrock/deployments/testnetL1
.PHONY: test-integration-testnet
```

to the Makefile underneath of https://github.com/celestiaorg/optimism/blob/cb828725e8df901a3cf97529f281babbd7fcb64f/Makefile#L116-L119

**Comment by jcstein** [comment]
I think we can close this in favor of #50

**Comment by tuxcanfly** [comment]
Closing in favor of #50

**Pull request closed without merging**
