### PR TITLE
devnet: bump local-celestia-devnet to v0.11.0-rc6

### LINKED ISSUE #136: devnet: update local-celestia-devnet to latest once RCs are a release

### PR DESCRIPTION
**Pull request by tuxcanfly**
## Overview

This PR updates the `local-celestia-devnet` version to `v0.11.0-rc6`.

While here, fix `op-batcher` dependencies and healthcheck.

Fixes #136 

## Checklist

- [x] New and updated code has appropriate documentation
- [x] New and updated code has new and/or updated testing
- [x] Required CI checks are passing
- [x] Visual proof for any user facing features like CLI or documentation updates
- [x] Linked issues closed with keywords

### CODE REVIEW

**Comment by jcstein** [comment]
utACK

# Docs that need updating with new version
- [ ] https://docs.celestia.org/developers/optimism-devnet/
- [ ] https://docs.celestia.org/developers/optimism/ (mostly [this](https://docs.celestia.org/developers/optimism/) caution flag)
cc @MSevey for vis

**Comment by MSevey** [comment]
> utACK
> 
> # Docs that need updating with new version
> * [ ]  https://docs.celestia.org/developers/optimism-devnet/
> * [ ]  https://docs.celestia.org/developers/optimism/ (mostly [this](https://docs.celestia.org/developers/optimism/) caution flag)
>   cc @MSevey for vis

@jcstein are these version updates in the docs variables yet? We can reapply what we did for app and node here. LMK how i can help.

**Review by MSevey — APPROVED** [review]
utack

**Comment by jcstein** [comment]
> @jcstein are these version updates in the docs variables yet? We can reapply what we did for app and node here. LMK how i can help.

I would appreciate your help adding them if you can, possibly when version is updated

Could be in constants.js and updated manually, or in workflow to use API to ping celestiaorg/optimism repo

**Review by jcstein — APPROVED** [review]
tested successfully on devnet

**Comment by jcstein** [comment]
but hitting [this on](https://app.warp.dev/block/e6oCgKZJok2dzF90ya1nDJ) arabica, but it is a local issue

`no matching manifest for linux/arm64/v8 in the manifest list entries` this may be related to a missing tag for `linux/arm64` on v0.11.0-rc6

fixed in ⬇️

**Pull request merged**
