### PR TITLE
deps: update devnet to latest version, v0.11.0-rc8

### LINKED ISSUE #174: bump version of local-celestia-devnet to v0.11.0-rc8
https://github.com/rollkit/local-celestia-devnet/pull/53#pullrequestreview-1532519382

then, re-release the latest version and edit release notes accordingly

### PR DESCRIPTION
**Pull request by jcstein**
## Overview

Resolves #174 

## Checklist

- [x] New and updated code has appropriate documentation
- [x] New and updated code has new and/or updated testing
- [x] Required CI checks are passing
- [x] Visual proof for any user facing features like CLI or documentation updates
- [x] Linked issues closed with keywords

### CODE REVIEW

**Comment by jcstein** [comment]
will have to test after build issues resolved here https://github.com/rollkit/local-celestia-devnet/actions

**Comment by jcstein** [comment]
https://app.warp.dev/block/2A3SS26XEZsLdyGmjyXdaJ

```
 ✘ da Error                                                                                     1.0s
1499Error response from daemon: manifest unknown
```

**Review by MSevey — APPROVED** [review]
utACK knowing that josh will test :-)

**Comment by jcstein** [comment]
I still need to test this, but documentation does not lead to people testing on main

**Comment by jcstein** [comment]
tested and updated docs.

**Pull request merged**
