### PR TITLE
op-server: bump celestia-openrpc to v0.3.0

### LINKED ISSUE #233: Incorrect setting of CELESTIA_NODE_AUTH_TOKEN in devnet-up.sh
In this line:
https://github.com/celestiaorg/optimism/blob/46d8e6a346cfb4581f4b616a0f463ea564e815d3/ops-bedrock/devnet-up.sh#L106

The container being referenced is `ops-bedrock-da-1`.
However, the actual container name is `ops-bedrock_da_1`.

image

### PR DESCRIPTION
**Pull request by tuxcanfly**
## Overview

This PR upgrades `celestia-openrpc` to `v0.3.0` so that it is compatible with `celestia-node` `v0.11.0`.

While here, also update the testnet script for `mocha-4`.

Resolves #233 

## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

### CODE REVIEW

**Review by MSevey — APPROVED** [review]
lgtm, what's the main reason to move to mocha over staying with arabica? Wouldn't it make sense to be on arabica-10?

**Comment by tuxcanfly** [comment]
I wanted to test for a partner who is running against `mocha`. We could maintain the testnet setup for both `arabica` and `mocha`. I'll test `arabica` and push it's update as well 👍🏽

**Comment by jcstein** [comment]
hmm, should we use mocha as default as it is the closest to a "production" environment?

**Review by jcstein — APPROVED** [review]
utACK - I will need to sync (async is okay) with you to update the docs for this after merged and released

**Comment by jcstein** [comment]
does this also close these issues @tuxcanfly ?

https://github.com/celestiaorg/optimism/issues/234
https://github.com/celestiaorg/optimism/issues/235

**Comment by jcstein** [comment]
I think it would be good to bump this to the latest version of celestia-node & local-celestia-devnet v0.12.0

**Comment by tuxcanfly** [comment]
@jcstein Yeah this fixes #235 will check about #234

**Comment by jcstein** [comment]
alternatively, maybe it would make more sense to ship this and then upgrade in a subsequent pr. not sure what is best

**Comment by tuxcanfly** [comment]
Going ahead with merging this as it's blocking integration with `celestia-node v0.11.0`

**Pull request merged**
